### ISSUE TITLE
Rewrite to tokio async

### ISSUE THREAD

**Issue by beeinger** [HerodotusDev/rust-accumulators#12]
- [X] async using Tokio
- [X] https://crates.io/crates/sqlx
- [ ] par_iter from: https://github.com/rayon-rs/rayon

Ref: https://tokio.rs/tokio/tutorial#:~:text=Speeding%20up%20CPU,practical%20example.

**Comment by rkdud007** [comment]
par_iter from: https://github.com/rayon-rs/rayon will leave it for now

need to think where to optimize it base on limitation below
1. directly to sql many part -- bcs using store as async trait
2. when order of node is important - bcs hash value can chnage
