### ISSUE TITLE
Solve path to files

### ISSUE THREAD

**Issue by beeinger** [HerodotusDev/rust-accumulators#23]
We need to access files in a few places in our code:
- config - to access the `ChainsConfig.toml` file
- db - to access database `migrations` folder
- accumulators - soon we will need to also access sqlite files for mmrs

And there is a problem with this, let's show this on the `config`:
```rust
static CONFIG_PATH: &str = "./ChainsConfig.toml";
static CONFIG: OnceCell<Config> = OnceCell::const_new();

pub async fn init() -> &'static Config {
    get().await
}

async fn get() -> &'static Config {
    CONFIG
        .get_or_init(|| async {
            let contents = fs::read_to_string(CONFIG_PATH).await.unwrap();
            let config: Config = toml::from_str(&contents).unwrap();
            config
        })
        .await
}
```

now everything works fine when run using `cargo make run`, cause it runs from root folder and the `./ChainsConfig.toml` path is valid
But when running tests `cargo run test` it seems they are being run differently, and instead of from the root, they have relative path to lib's folder, so `./ChainsConfig.toml` does not exist and we get a panic when unwraping

TODO:

- [ ] a solution that will always work, both when doing `cargo make run` and `cargo make test`, we need a way to access a path relative to the root of the repository

**Comment by rkdud007** [comment]
solved in `indexer` repo
