### ISSUE TITLE
Create tests for Poseidon hashing, both on rust and ts accumulator

### ISSUE THREAD

**Issue by maaasyn** [HerodotusDev/rust-accumulators#41]
- It's absolutly crusial for our hasher to give the same hashes for the same values on TS-accumulator and RUST-accumulatr. I've done some unit tests on ts-accumulator for keccak: https://github.com/HerodotusDev/accumulators/pull/72/files and I've done same tests for keccak on rust https://github.com/HerodotusDev/rust-accumulators/pull/40.

- We still need to test the building of trees with poseidon. The test I would like to see should be done both on ts accumulator and rust accumulator. We can copy paste the test scenarious which I done for keccak, but replace the hashes for the new one. The ts-accumulator detereminates what is consider valid hash.

**Comment by rkdud007** [comment]
close with #42
